ALTER TABLE admin ADD COLUMN office VARCHAR(10) NOT NULL;
ALTER TABLE admin ADD COLUMN office_visible BOOL NOT NULL;
ALTER TABLE admin ADD COLUMN email VARCHAR(100) NOT NULL;
ALTER TABLE admin ADD COLUMN email_visible BOOL NOT NULL;
ALTER TABLE admin ADD COLUMN phone VARCHAR(15) NOT NULL;
ALTER TABLE admin ADD COLUMN phone_visible BOOL NOT NULL;
ALTER TABLE admin ADD COLUMN photo VARCHAR(100) NOT NULL;

ALTER TABLE admin DROP CONSTRAINT admin_contact_fkey;

ALTER TABLE admin DROP COLUMN contact;

DROP TABLE IF EXISTS contact;

ALTER TABLE admin DROP CONSTRAINT admin_role_check;
ALTER TABLE admin ADD CONSTRAINT admin_role_check CHECK (role in ('ROLE_MODERATOR', 'ROLE_ADMIN'));